// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FlashNotificationController from "./flash_notification_controller"
application.register("flash-notification", FlashNotificationController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)
